#!/bin/bash

host="$1"

# Check for existing GPIO handler and kill.
pids=$(sudo ps aux | grep 'python.*scratch_.*gpio_handler.py' | grep -v grep | awk '{print $2}')
# | xargs echo sudo kill -KILL
if [ "${pids}" ]; then
  set -- ${pids}
  pids="$*"
  echo "Killing existing python GPIO pids: ${pids} ..."
  sudo kill -KILL ${pids}
fi

# Start Python GPIO handler script.
# host="192.168.1.84"
echo "Starting Scratch morse GPIO handler..."
sudo python /home/pi/simplesi_scratch_handler/scratch_morse_gpio_handler.py ${host} &

# Start Scratch and project with remote sensors enabled.
# myproj="rsc"
# myproj="zed"
# myproj="morse"
# scratch --document "/home/pi/Documents/Scratch Projects/${myproj}.sb" &
